spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: default

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: Password
    jdbc-url: jdbc:postgresql://localhost:5432/testdb1
  seconddatasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/testdb2
    username: root
    password: Password
